## data
train_file: data/training_example123.json
dev_file: data/dev_example.json


## training
base_model: bert-base-uncased
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
adam_eps: 1.0e-8
weight_decay: 0.0
max_grad_norm: 2.0
lr: 2.0e-5
warmup_steps: 1237
max_train_epochs: 40
seed: 19980406
gradient_accumulation_steps: 1
val_check_interval: 1.0
num_hard_negative_ctx: 20
num_other_negative_ctx: 20
num_docs_per_sample: 20
num_pos_ctx: 10
